services:
  adonis-mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - $PWD/data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: ${DB_ALLOW_EMPTY_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    networks:
      - api-network
  adonis-api:
    container_name: "adonis-api-app"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3333:3333"
    depends_on:
      - adonis-mysql
    networks:
      - api-network

networks:
  api-network:
